import { ensureEnv } from '@take-out/helpers'

if (typeof window !== 'undefined') {
  throw new Error(`This is a server-only file`)
}

// 🔒 start - this is generated by "bun env:update"
export const BETTER_AUTH_SECRET = ensureEnv('BETTER_AUTH_SECRET')
export const BETTER_AUTH_URL = ensureEnv('BETTER_AUTH_URL')
export const ONE_SERVER_URL = ensureEnv('ONE_SERVER_URL')
export const VITE_ZERO_HOSTNAME = ensureEnv('VITE_ZERO_HOSTNAME', "")
export const VITE_WEB_HOSTNAME = ensureEnv('VITE_WEB_HOSTNAME', "")
export const ZERO_VERSION = ensureEnv('ZERO_VERSION')
export const ZERO_NUM_SYNC_WORKERS = ensureEnv('ZERO_NUM_SYNC_WORKERS', "2")
export const ZERO_CVR_MAX_CONNS = ensureEnv('ZERO_CVR_MAX_CONNS', "4")
export const ZERO_UPSTREAM_MAX_CONNS = ensureEnv('ZERO_UPSTREAM_MAX_CONNS', "8")
export const ZERO_PER_USER_MUTATION_LIMIT_MAX = ensureEnv('ZERO_PER_USER_MUTATION_LIMIT_MAX', "30")
export const ZERO_PER_USER_MUTATION_LIMIT_WINDOW_MS = ensureEnv('ZERO_PER_USER_MUTATION_LIMIT_WINDOW_MS', "60000")
export const ZERO_MUTATE_FORWARD_COOKIES = ensureEnv('ZERO_MUTATE_FORWARD_COOKIES', "true")
export const ZERO_QUERY_FORWARD_COOKIES = ensureEnv('ZERO_QUERY_FORWARD_COOKIES', "true")
export const ZERO_APP_PUBLICATIONS = ensureEnv('ZERO_APP_PUBLICATIONS', "zero_takeout")
export const CLOUDFLARE_R2_ENDPOINT = ensureEnv('CLOUDFLARE_R2_ENDPOINT', "")
export const CLOUDFLARE_R2_BUCKET = ensureEnv('CLOUDFLARE_R2_BUCKET', "")
export const CLOUDFLARE_R2_ACCESS_KEY = ensureEnv('CLOUDFLARE_R2_ACCESS_KEY', "")
export const CLOUDFLARE_R2_SECRET_KEY = ensureEnv('CLOUDFLARE_R2_SECRET_KEY', "")
export const BILLING_PROVIDER = ensureEnv('BILLING_PROVIDER', "manual")
export const BILLING_WEBHOOK_SECRET = ensureEnv('BILLING_WEBHOOK_SECRET', "")
export const CRON_SECRET = ensureEnv('CRON_SECRET', "")
export const EXTRA_TRUSTED_ORIGINS = ensureEnv('EXTRA_TRUSTED_ORIGINS', "")
export const GOOGLE_CLIENT_ID = ensureEnv('GOOGLE_CLIENT_ID', "")
export const GOOGLE_CLIENT_SECRET = ensureEnv('GOOGLE_CLIENT_SECRET', "")
// 🔒 end - this is generated by "bun env:update"

// database urls set conditionally based on deployment
// use bracket notation to prevent build-time inlining

/**
 * A conexão do **app server** com o Postgres — apesar do nome, que veio do starter.
 * É a que `src/database/database.ts` usa.
 *
 * `DATABASE_URL` é o fallback porque a integração Neon↔Vercel injeta as variáveis com
 * os nomes dela, e `ZERO_UPSTREAM_DB` não está entre eles. Ler o nome padrão evita
 * copiar o valor à mão para um segundo campo — cópia que ficaria velha na primeira
 * rotação de credencial feita pelo Neon.
 *
 * ⚠️ **Na Vercel isto tem que ser a URL COM pooler** (é o que `DATABASE_URL` traz):
 * cada função serverless abre conexão própria, e sem o PgBouncer o Neon esgota.
 * O oposto vale para o zero-cache e para as migrations, que precisam da direta
 * (`DATABASE_URL_UNPOOLED`) porque replicação lógica não passa por pooler.
 */
export const ZERO_UPSTREAM_DB =
  process.env['ZERO_UPSTREAM_DB'] || process.env['DATABASE_URL'] || ''

// usados só pelo zero-cache, que roda no Fly com env próprio
export const ZERO_CVR_DB = process.env['ZERO_CVR_DB'] || ''
export const ZERO_CHANGE_DB = process.env['ZERO_CHANGE_DB'] || ''
