import { ensureEnv } from '@take-out/helpers'

if (typeof window !== 'undefined') {
  throw new Error(`This is a server-only file`)
}

// 🔒 start - this is generated by "bun env:update"
export const BETTER_AUTH_SECRET = ensureEnv('BETTER_AUTH_SECRET')
export const BETTER_AUTH_URL = ensureEnv('BETTER_AUTH_URL')
export const ONE_SERVER_URL = ensureEnv('ONE_SERVER_URL')
export const VITE_WEB_HOSTNAME = ensureEnv('VITE_WEB_HOSTNAME', "")
export const CLOUDFLARE_R2_ENDPOINT = ensureEnv('CLOUDFLARE_R2_ENDPOINT', "")
export const CLOUDFLARE_R2_BUCKET = ensureEnv('CLOUDFLARE_R2_BUCKET', "")
export const CLOUDFLARE_R2_ACCESS_KEY = ensureEnv('CLOUDFLARE_R2_ACCESS_KEY', "")
export const CLOUDFLARE_R2_SECRET_KEY = ensureEnv('CLOUDFLARE_R2_SECRET_KEY', "")
export const BILLING_PROVIDER = ensureEnv('BILLING_PROVIDER', "manual")
export const BILLING_WEBHOOK_SECRET = ensureEnv('BILLING_WEBHOOK_SECRET', "")
export const STRIPE_SECRET_KEY = ensureEnv('STRIPE_SECRET_KEY', "")
export const STRIPE_WEBHOOK_SECRET = ensureEnv('STRIPE_WEBHOOK_SECRET', "")
export const CRON_SECRET = ensureEnv('CRON_SECRET', "")
export const EXTRA_TRUSTED_ORIGINS = ensureEnv('EXTRA_TRUSTED_ORIGINS', "")
export const GOOGLE_CLIENT_ID = ensureEnv('GOOGLE_CLIENT_ID', "")
export const GOOGLE_CLIENT_SECRET = ensureEnv('GOOGLE_CLIENT_SECRET', "")
// 🔒 end - this is generated by "bun env:update"

// database urls set conditionally based on deployment
// use bracket notation to prevent build-time inlining

/**
 * A conexão com o Postgres.
 *
 * 🔴 **`DATABASE_URL` vem primeiro, `ZERO_UPSTREAM_DB` é só compatibilidade.** A ordem
 * era a inversa enquanto o zero-cache existia. Inverter antes de tirar a variável velha
 * das máquinas é o que evita um outage de sintoma confuso: enquanto as duas existirem, a
 * nova ganha; quando `ZERO_UPSTREAM_DB` sumir do `app.env`, nada muda.
 *
 * O nome antigo fica por um ciclo de deploy e depois sai.
 */
export const DATABASE_URL =
  process.env['DATABASE_URL'] || process.env['ZERO_UPSTREAM_DB'] || ''

/** @deprecated Use `DATABASE_URL`. Mantido enquanto as máquinas têm o nome antigo. */
export const ZERO_UPSTREAM_DB = DATABASE_URL
